#!/bin/bash

# vaatab süsteemist aega
aeg=$(date +%H)
# kasutaja
var=$(whoami)

# valib vastuse vastavalt ajale
if [ $aeg -ge 6 -a $aeg -lt 12 ]; then
        echo "Tere hommikust, $var!"
elif [ $aeg -ge 12 -a $aeg -lt 18 ]; then
        echo "Tere paevast, $var!"
elif [ $aeg -ge 18 -a $aeg -lt 22 ]; then
        echo "Tere ohtust, $var!"
elif [ $aeg -ge 22 -a $aeg -lt 24 ] || [ $aeg -ge 0 -a $aeg -lt 6 ]; then
        echo "Head ood, $var!"
else
        echo "Vale sisend"
fi

