#!/bin/bash

#Date commandiga näitab nädalapäeva, kuud koos päevaga ja aastat

#Date commandiga näitab tundi ja minuteid

#cal-iga näitab kalendrit

echo "Today is $(date +'%A, %B %d, %Y')"

echo "Time is $(date +%H:%M)"

echo "Calendar of$(cal)"

